services:
  - type: web
    name: taskflow-django
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn taskflow_django.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: taskflow_django.settings
      - key: PYTHON_VERSION
        value: 3.10
